server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jdbc
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org:
      springframework: INFO
  file:
    path: /log/myapp.log